FROM python:3.11.13

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE $PORT

CMD ["gunicorn", "--workers=4", "--bind", "0.0.0.0:$PORT", "app:app"]

# Note: Ensure that the PORT environment variable is set when running the container.